apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-event-listener
  namespace: tekton-system
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-event-listener
      interceptors:
        - name: github-webhook
          ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: secretRef
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                - push
                - pull_request
      bindings:
        - ref: github-trigger-binding
      template:
        ref: github-trigger-template