apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-trigger-binding
  namespace: tekton-system
spec:
  params:
    - name: SOURCE_REVISION
      value: $(body.after)
    - name: GITHUB_REPO_URL
      value: $(body.repository.clone_url)